version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.7.2
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 5.0.0
    - 5.0.1
  - dependency-name: rails
    versions:
    - 6.1.3
    - 6.1.3
    - 6.1.3
  - dependency-name: activestorage
    versions:
    - 6.1.3
  - dependency-name: activesupport
    versions:
    - 6.1.3
  - dependency-name: jbuilder
    versions:
    - 2.11.2
