version: "3"
services:
  db:
    image: mysql:8.0
    # image: ryoishii/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d

  web:
    # image: ryoishii/tomotabi_web:latest
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - BUNDLE_PATH=/bundle
volumes:
  bundle_path:
